### ISSUE TITLE
Rename and rebrand the project

### ISSUE THREAD

**Issue by paulofreitas** [paulofreitas/geodata-br#27]
# Tasks
## Project
- [x] Rename the GitHub project to *geodata-br*
- [x] Update the project README file
## Data
- [x] Rename data files to use translatable file names like _brazil.{ext}_ (en), _brasil.{ext}_, etc.
- [ ] Update XML data files to use translatable dataset names like _brazil\_{year}_, _brasil\_{year}_, etc.
## Code
- [x] Rename package to *geodatabr*
- [x] Update every script to use the new package namespace
- [x] Update setup script
