### ISSUE TITLE
Use SIDRA as data source

### ISSUE THREAD

**Issue by paulofreitas** [paulofreitas/geodata-br#38]
Since this repository is now focused on providing only the most-updated geographic data, it would be helpful to use [SIDRA](https://sidra.ibge.gov.br/) (*Sistema IBGE de Recuperação Automática*) as its main data source.

**Tasks:** *(work in progress)*

- [ ] Rename `geodatabr.databases` package to `geodatabr.dataset`
- [ ] Improve `geodatabr.core.helpers.filesystem` module
  - [ ] Write new `CacheDirectory` and `CacheFile` classes to store cached files at `$HOME`
