### ISSUE TITLE
Unify formats and exporters packages into a new encoders package

### ISSUE THREAD

**Issue by paulofreitas** [paulofreitas/geodata-br#39]
Simple is better than complex. Let's unify `geodatabr.formats` and `geodatabr.exporters` packages into a new simplified `geodatabr.encoders` package.

***Tasks***: *(work-in-progress)*

- [x] <s>Rename `geodatabr.exporters` package to `geodatabr.encoders`</s> (Done in commit d7389d63153bd139b37c80f8d83396a12db8e43c)
  - Rename `Exporter` class to `Encoder`
  - Rename `Encoder.export()` method to `Encoder.encode()`
  - Rename `Encoder.exportToFile()` method to `Encoder.encodeToFile()`
  - Rename `ExporterFactory` class to `EncoderFactory`
  - Rename `ExportError` class to `EncodeError`
  - Rename `UnknownExporterError` class to `UnknownEncoderError`
  - Rename `CsvExporter` class to `CsvEncoder`
  - Rename `FirebirdExporter` class to `FirebirdEncoder`
  - Rename `JsonExporter` class to `JsonEncoder`
  - Rename `MessagePackExporter` class to `MessagePackEncoder`
  - Rename `PlistExporter` class to `PropertyListEncoder`
  - Rename `SqlExporter` class to `SqlEncoder`
  - Rename `Sqlite3Exporter` class to `Sqlite3Encoder`
  - Rename `TsvExporter` class to `TsvEncoder`
  - Rename `XmlExporter` class to `XmlEncoder`
  - Rename `YamlExporter` class to `YamlEncoder`
  - Rename concrete encoder classes `export()` method to `encode()`
- [x] <s>Merge `geodatabr.formats` package modules into `geodatabr.encoders` package</s> (Done in commit 51d1f19139b4c4aff61f4e2c26e1debb9e3a8f98)
  - Move `Format`, `FormatFactory`, `FormatRepository`, `FormatError` and `UnknownFormatError` classes to `geodatabr.encoders` package
  - Move concrete format classes to `geodatabr.encoders` modules
  - Change `geodatabr.encoders.plist`, `geodatabr.encoders.sql` and `geodatabr.encoders.yaml` encoders modules to packages
  - Move `geodatabr.formats.plist.utils` module to `geodatabr.encoders.plist` package
  - Move `geodatabr.formats.sql.utils` module to `geodatabr.encoders.sql` package
  - Move `geodatabr.formats.yaml.utils` module to `geodatabr.encoders.yaml` package
  - Move `geodatabr.formats.dat` and `geodatabr.formats.xls` format modules to `geodatabr.encoders` package
- [ ] Simplify `geodatabr.encoders` package
  - Rename `Format` class to `EncoderFormat`
  - Remove unneeded `EncoderFormat.isExportable()` method
  - Rename `FormatFactory` class to `EncoderFormatFactory`
  - Rename `FormatRepository` class to `EncoderFormatRepository`
  - Remove unneeded `EncoderFormatRepository.findExportableFormats()` method
  - Rename `EncoderFormatRepository.listExportableFormatNames()` method to `EncoderFormatRepository.listNames()`
  - Rename `EncoderFormatRepository.groupExportableFormatsByType()` method to `EncoderFormatRepository.groupByType()`
  - Fix `EncoderFormatRepository.listNames()` and `EncoderFormatRepository.groupByType()` methods to return `list`s
  - Change `EncoderFormatRepository.listNames()` and `EncoderFormatRepository.groupByType()` methods to iterate over `Encoder.childs()` formats
  - Remove unused `FormatError` class
  - Rename `UnknownFormatError` class to `UnknownEncoderFormatError`
  - Change `UnknownEncoderFormatError` and `UnknownEncoderError` classes to subclass `Exception` class
  - Remove `isExportable()` and `isParseable()` methods from concrete encoder format classes
